### ISSUE TITLE
Separate local parameter names from system parameter names

### ISSUE THREAD

**Issue by robbr48** [Hopsan/hopsan#1694]
When a system parameter and a local parameter in a component have the same name, it is unclear which one will be used. 

Suggestions:
- Use system parameters by default
- Use local parameter if system parameter with same name do not exist
- Add special syntax for force using local parameters

**Comment by peterNordin** [comment]
Related #1590

**Comment by peterNordin** [comment]
A resonable solution might be for the checkmodelbeforesimulation funcrion to abort if it finds a risk for  variable name collission.

If no collision exist you van use the system parameter name as usual. But if a local parameter with the same name exists. Then you must prepend it with 'this.' or 'self.' 

You could also require 'parent.' for system parameters, but I dont like this.

An other solution would be ../systemparameter,  and ./localparameter, like file paths. Then you could reference variables higher up or deeper down. But I dont really think this is a goog idea either.

**Comment by robbr48** [comment]
I like the 'self.' suggestion. But perhaps it should be needed even when there is no name collision, just for clarity? What will otherwise happen if you add a system parameter afterwards, causing a name collision? Should you not be allowed to add the system parameter? Or should it check just before simulation?

**Comment by peterNordin** [comment]
Yesm good idea.  self.NAME shal be required for local parameters. But we need backward compatibility with older models, so some collision check is needed, and a warning should be printed if,  self. Is missing

**Comment by robbr48** [comment]
The self.X solution is problematic with HCOM. SymHop cannot evaluate for example "2*self.X+5", since it has no knowledge about which component self.X originates from. Just having "self.X" as parameter value works, since it can be replaced directly by HCOM. But expressions require SymHop evaluations. Not sure how to solve this.

I guess the same problem already exists though. It will try system parameters, and if not found there it will fail.

**Comment by peterNordin** [comment]
The parameter evaluation uses numhop (should really call this something else) model embedded script.
But the purpose of hcom is to be a model external script. So 'self' should not be relevant there, I think. Hcom is for pre/post processing and automation. NumHop for internal model calculation (right now initialization only) so in this case having self. makes sense.
Or am I missing some use case ?

**Comment by peterNordin** [comment]
Ok, I get it now. If Hcom asks for the parameter value, then it will get the string including self. which it doea not understand.

But this should be easy to solve.

* Add a function that getsthe resolved parameter "value", a string where self. has been replaced withthe component/port name.
* Or make the component calculate the nummeric value itself (using embedded script)
