### ISSUE TITLE
Animation crashes when variable is NaN or inf

### ISSUE THREAD

**Issue by robbr48** [Hopsan/hopsan#1695]
Only solution is to check all variables for illegal data. It will reduce performance, but stability is more important.

Suggestion:
- Replay animation: Check all varaibles for NaN or Inf before playing
- Realtime animation: Check all variables for NaN or Inf at every step
- Indicate somehow to the user that something is wrong (highlighting component, stopping animation or similar)

**Comment by peterNordin** [comment]
Last time I looked into finding NaN, i learned that there is no reliable cross-platform / cross-compiler wat to detect this. There are some tricks that will likely work for our particular case on Windows. But there is no guarantee that the same will always work. 
But I agree that it would be nice to dete t this after (or during) a simulation.
but this should be something that is not on by default, there is likely a significant slowdown, at least for large models.
If we can find a reliable way to check for inf and none, then we could check all data while collecting it from the core. For realtime every step would need to be checked.

But must really all data be checked or only the data that is used in animation.
Could maybe check on-the-fly in that case

**Comment by robbr48** [comment]
C++11 has functions for detecting both [NaN](http://en.cppreference.com/w/cpp/numeric/math/isnan) and [Inf](http://en.cppreference.com/w/cpp/numeric/math/isinf).

We only need to check variables used for animation, which should not be too many.

It needs to be on by default. Nobody will turn this on manually, especially not inexperienced users. Let's implement it and see how much it affects performance.
