### ISSUE TITLE
Recompilation dialog is annoying

### ISSUE THREAD

**Issue by robbr48** [Hopsan/hopsan#1723]
Especially if a large number of libraries are recompiled successfully at startup. User then need to close each dialog individually. Also enter button does not seem to work, so user needs to click on "close" in every dialog.

Suggestion: Use one single new dialog for displaying all recompilation. Output can be opened by clicking a button. Dialog should close automatically after X seconds if all recompilations were successful.

**Comment by peterNordin** [comment]
Yes, this is annoying. I have already added a function that will auto close the dialogs on success. It is not finnished yet, because there is currently no reliable way to know if a compilation was actually successfull.  But that should be solvable.

**Comment by peterNordin** [comment]
#1532

**Comment by robbr48** [comment]
I guess the reliable way is to delete the dll/so file before compilation and check if a new one is created. If it is generated but still cannot be loaded it could give message like "compilation successful but library is still not loadable" (although this should in theory never happen).

**Comment by peterNordin** [comment]
Maybe we should just clear the entire output directory.
Might be a problem if users put their own library files there though.

**Comment by robbr48** [comment]
That is not a good idea I think. What if someone attempts to export directly into "My Documents" or "Program Files"? We should remove files that we know will be generated by the export though

**Comment by peterNordin** [comment]
Yes that would be evil, clearing build files and fmu should be enough
