### ISSUE TITLE
Allow unconnected ports in disabled components

### ISSUE THREAD

**Issue by robbr48** [Hopsan/hopsan#1765]
**Is your improvement request related to a problem? Please describe.**
Disabled components should be allowed to have unconnected ports.

**Describe the solution you'd like**
Do not run pre-simulation checks for disabled components.

**Comment by peterNordin** [comment]
What should happen if you have a disabled component connected to a enabled one
Lets say its a power port connection. Then allowing that connecting would result in simulation returning unexpected values.
I assume that you mean, allow disabled components that may or may not be connected. But only if any connections are to other disabled components.

Signal read ports on disabled components could be allowed to be connected though. But better not.

**Comment by robbr48** [comment]
This is already allowed. Input variables on the enabled component will keep their start values during the entire simulation. If the enabled component is of Q-type, this corresponds to a zero pressure source. If the enabled component is of C-type, it will be like a plugged connection. Allowing such connections is useful in many cases, if you for example want to test a hydraulic transmission and disable the anti-cavitation components without unconnecting them.

**Comment by peterNordin** [comment]
I don't understand about power ports. If a connection exists between a C and Q component. And the Q component have non−stationary start values. What will happen then? Is the disabled component ports replaced with 'plugs' or 'constant pressure' component. Or will the results of the simulation be similar if either C or Q is not simulated? I have not thought about these sort of things for a while.....

**Comment by peterNordin** [comment]
But what if those start values have been disabled? Or you have non-zero values. I think this is going to be strange. But I guess its up to the user to decide for them selves.

**Comment by robbr48** [comment]
All node variables should have default values set to zero, so in most cases it will work as expected. But yes, the user needs to know what he/she is doing when disabling something that is connected.
