### ISSUE TITLE
Min and max parameters in slider component

### ISSUE THREAD

**Issue by robbr48** [Hopsan/hopsan#1785]
**Is your improvement request related to a problem? Please describe.**
Slider component always outputs values from 0 to 1. They need to be converted using signal components.

**Describe the solution you'd like**
Add parameters for min and max value.

**Comment by peterNordin** [comment]
@robbr48 has this been solved? Maybe by #1814

**Comment by robbr48** [comment]
Yes. Resolved by #1814.
