### ISSUE TITLE
Plot unit selection does not allow a unit with scale one other than the base unit

### ISSUE THREAD

**Issue by MarkusBagge** [Hopsan/hopsan#1799]
**Describe the bug**
If selecting a unit with scale 1 that is not the base unit, the base unit will be used. Base unit for quantity Power is J/s. It its not possible to select unit "W" which also has scale 1.

**To Reproduce**
1. Add a constant and connect to a Scope in a model.
2. Set the quantity of the constant to Power.
3. Simulate the model and open the Scope.
4. Use the context menu and change unit to "W".
5. J/s will be displayed on the Y-axis.

**Expected behavior**
The y-axis shows "W".

**Hopsan version:**
 - OS: Debian 9
 - Version:  HopsanCore 64-bit, Version: 2.10.0.20170101.0001
                  HopsanGUI 64-bit, Version: 2.10.0.20181026.2220
 - Build: Compiled from commit 1e379d3176cee4284d6435151db6277fc6e0611d.

**Additional information**
Issue seems to arise from PlotCurve.cpp. Below appears to solve the issue but maybe introduces a new one? Don't understand why the isScaleOne() check is there.

Rewriting from
```
void PlotCurve::setCurveDataUnitScale(const UnitConverter &rUS)
{
    if (rUS.isEmpty())
    {
        resetCurveDataUnitScale();
    }
    else
    {
        mCurveDataUnitScale = rUS;

        // Clear the custom scale if it is one and we have a data unit
        if (!getDataUnit().isEmpty() && mCurveDataUnitScale.isScaleOne())
        {
            resetCurveDataUnitScale();
        }
        else
        {
            updateCurve();
            //! @todo shouldn't these be triggered by signal in update curve?
            mpParentPlotArea->replot();
        }
    }
}
```
to 
```
void PlotCurve::setCurveDataUnitScale(const UnitConverter &rUS)
{
    if (rUS.isEmpty())
    {
        mCurveDataUnitScale.clear();
    }
    else
    {
        mCurveDataUnitScale = rUS;
    }
    updateCurve();
    //! @todo shouldn't these be triggered by signal in update curve?
    mpParentPlotArea->replot();
}
```

**Comment by peterNordin** [comment]
This code is quite complex, that check is to reset custom curve scales that can be set directly on the curve. For instance if you scale a curve with unit meter, with 42, it will show [42 * m] and then when you reset to 1  it should not show [1 * m] but reset to the actually selected scale. 
But yes the check was incorrect, it should only work on "plain numeric scales"
