### ISSUE TITLE
Sort units by scale

### ISSUE THREAD

**Issue by MarkusBagge** [Hopsan/hopsan#1802]
**Is your improvement request related to a problem? Please describe.**
When selecting custom units in different menus, one would expect them to be sorted by scale like "Pa, kPa, bar, MPa...". There is no sorting today so they appear in no specific order. 

**Describe the solution you'd like**
This is basically about returning a sorted list in rUnitScales by modifying
void Configuration::getUnitScales(const QString &rQuantity, QList<UnitConverter> &rUnitScales)
...since this is used to populated the menus.

**Describe alternatives you've considered**
Sorting in suggested commit below is done when getting values. Can also be done when setting them I guess.

**Comment by peterNordin** [comment]
Related to #1483

**Comment by peterNordin** [comment]
Yes please, make pull request, looked over the code, seems resonable. Will review PR more thoroughly

**Comment by MarkusBagge** [comment]
Pull request #1809
