### ISSUE TITLE
System parameteres in expressions are not added when pasting components

### ISSUE THREAD

**Issue by robbr48** [Hopsan/hopsan#1808]
**Describe the bug**
When pasting a component with a parameter mapped to a system parameter, the system parameter is added to the system if it does not already exist. However, if the system parameter is used in a NumHop expression (e.g. "-x"), it is not added.

**To Reproduce**
*If the bug can be reproduce, please give the steps taken to reproduce the behavior:*
1. Add component A
2. Add system paramter X
3. Set a parameter in A to -X
4. Copy component A
5. Create a new model
6. Paste component A
7. It is not possible to simulate the model, since "X" is not available

**Expected behavior**
X should be added to the target model.

**Comment by peterNordin** [comment]
Depends on peterNordin/libNumHop#2
