### ISSUE TITLE
FMI/fmi_import_context.h: No such file or directory

### ISSUE THREAD

**Issue by Netzahualcoyotl** [Hopsan/hopsan#1827]
Hi, Hospan developers

I am trying to run Hospan in ubuntu 18.04.01, using the next procedure:
1. To install GCC (and some other tools) on Ubuntu run apt-get install build-essential.
2. The following packages seem to include all necessary components: apt-get install python-dev, qtbase5-dev, libqt5webkit5-dev, libqt5svg5-dev, qtmultimedia5-dev, libqt5opengl5-dev, libhdf5-dev, unzip, cmake, libtool-bin, automake, pkg-config
Note! What packages are needed may change between OS versions (due to repackaging), you may need additional packages.
3. instead of Download Qt Creator from your package repository or a newer version from http://download.qt.io/official_releases/qtcreator/
I use sudo apt-get install qtcreator.

after it 

I install 

 sudo apt-get install python3-venv

Then I have excecuted the line

python3 -m venv venv

and after it I have installed the next packages

sudo apt-get install qt5-default qttools5-dev-tools qtmultimedia5-dev
sudo apt-get install libqt5svg5-dev libqt5xmlpatterns5-dev

then I have folowed the next lines

Build the required and desired optional dependencies first
Open the HopsanNG.pro project file. Make sure that you are using the same qmake version and build tool chain as you used to build the dependencies.
Go to Projects->Build and under Build Steps enter the Make argument: -j4 to speed up compilation using 4 cores. (Optional)
It is recommended to activate shadow build for both debug and release, (you will likely be able to use the default shadow build location) Shadow build means that all of the build files will be put someplace else to avoid clutter
qmake will automatically search for the previously build dependencies in the Dependencies directory. Each dependency have a .pri file that specify the needed compilation and linking variables.
Before you compile, run qmake on the HopsanNG project (right click), to see the qmake messages, (you will see if all dependencies were found correctly). This information is shown in the compile tab.
Build the project in either debug or release mode
If you want to start HopsanGUI through Qt Creator, go into the left panel Projects->Run and change the Run configuration

When I excecute qmake the process exited normally

When I build project HospanNG display this error

In file included from ../../hopsan/HopsanGenerator/src/HopsanGeneratorLib.cpp:37:0:
../../hopsan/HopsanGenerator/include/generators/HopsanFMIGenerator.h:34:10: fatal error: FMI/fmi_import_context.h: No such file or directory
 #include "FMI/fmi_import_context.h"

Can you help me?
With some procedure please.

![screenshot from 2019-01-23 12-00-57](https://user-images.githubusercontent.com/6040219/51627177-f314c400-1f06-11e9-8702-64c43d41a0dc.png)

**Comment by peterNordin** [comment]
Hi
I know it's not super obvious, but there are prebuilt packages for Ubuntu here: https://flumes.iei.liu.se/hopsan/files/releases/official
For 18.04 you should use the one called bionic, choose amd64 for 64bit system or i386 for 32 bit.

However, if you still want to build yourself. Did you run "git submodule update --init" after cloning the code? It will check out all of the dependencies. While most of them are available in the Ubuntu package repo, one is not. The FMILibrary that you are having trouble with. Run the setupFMILibrary.sh script in the Dependencies subdirectory to build it (cmake required).

You may also need to run some of the other setup scripts, but I actually think that most are available in the repo.

**Comment by peterNordin** [comment]
You must also run the setupKatex script. All other are a ailable in the repo. If for some reason qwt dev packages are not installed. Then you must also run setupQwt.sh.

I recommend that you do not try to build the PythonQt dependency. It usually causes problems and the build in pyhon support is not so good in Hopsan anyway.

Please let me know if you run onto more problems. (I know that the build instructions need to be updated)

**Comment by peterNordin** [comment]
I looked over your initial post in a bit more detail and it seem like you already had followed my suggestions about running setupFMILibrary. But I realized that there is no check if the expected files were actually found, so qmake wont complain. 

Can you check inside the Dependencies directory in the hopsan code (git clone) directory.
There you should have the FMILibrary_code, FMILibrary_build and FMILibrary directories.
If "FMILibrary" is missing or empty, then the library was not built, or built in the wrong place.

**Comment by Netzahualcoyotl** [comment]
Hello, Peter Nordin

Thank you for your time, I also install Hopsan from Ubuntu Software and it does not start it just not show any message simpply dont open the softwate.


Folowing your Instructions to show what are inside the Hopsan/dependencies directory I take a picture of the folder, but I can not see that FMILybrary or I can not identify what is that library.

netza@netzacomputer:~/Hopsan/hopsan/Dependencies$ ls
cppzmq                         PythonQt3.0_MinGW.patch  setupKatex.sh
discount-2.1.8-msys.patch      pythonqt.pri             setupMatio.bat
discount_code                  qwt-build.patch          setupPythonQt.bat
discount-mingw-building.patch  qwt_code                 setupPythonQt.sh
discount.pri                   qwt.pri                  setupQwt.bat
fmilibrary-c99.patch           releases                 setupQwt.sh
fmilibrary.pri                 setHopsanBuildPaths.bat  setupZeroMQ.bat
git-archive-all                setHopsanBuildPaths.sh   setupZeroMQ.sh
hdf5_code                      setupAll.sh              tclap
hdf5.pri                       setupDiscount.bat        tools
katex_code                     setupDiscount.sh         zeromq-check.pri
matio-1.5.2.patch              setupFMILibrary.bat      zeromq_code
matio_code                     setupFMILibrary.sh       zeromq.pri
msgpack-c                      setupHDF5.bat
msgpack.pri                    setupKatex.bat

**Comment by Netzahualcoyotl** [comment]
Hello, Peter Nnordin
If I install from this bionic amd 64 version https://flumes.iei.liu.se/hopsan/files/releases/official/2.10.0/ubuntu/
it work.
Thank you, my best regards
