### ISSUE TITLE
generationDateAndTime of exported fmu not valid

### ISSUE THREAD

**Issue by ebw44** [Hopsan/hopsan#1846]
Using fmpy as well as [rust fmi library](https://gitlab.com/jondo2010/rust-fmi) I have issue with the format of the generationDateAndTime="2019-05-10_16_10" in the fmiModelDescription in the modelDescription.xml

fmpy returns attribute 'generationDateAndTime': '2019-05-10_16_10' is not a valid value of the atomic type 'xs:dateTime'.

replacing "2019-05-10_16_10" by "2017-04-11T00:38:04" fix the problem for fmpy.

 - OS: Windows 10
 - Version: HopsanCore 64-bit, Version: 2.11.0.20190124.2106
                       HopsanGUI 64-bit, Version: 2.11.0.20190124.2106
 - Build: **official** build downloaded from the web page

**Comment by peterNordin** [comment]
@ebw44 I uploaded a snapshot release to https://flumes.iei.liu.se/hopsan/files/releases/experimental/ if you want to test this fix.

**Comment by ebw44** [comment]
@peterNordin the snapshot fixes the generationDateAndTime  issue.
