### ISSUE TITLE
Import Model Parameter File (.hpf)

### ISSUE THREAD

**Issue by IngoSt** [Hopsan/hopsan#1850]
When inporting a .hpf via
Import --> Load model parameters

No terminal output confirming the successful loading will be stated on the Terminal window. It would be good to see there that the model (e.g. with details that XX parameters in YY components have been updated/overwritten) has been laoded & updated

**Comment by peterNordin** [comment]
@IngoSt and @robbr48 I was thinking that this would be an easy thing to fix, but I noticed some additional issues that need to be fixed, and I need your input for a design decision. 

In the HopsanCore, the import and export of parameters is handled at the system level, so you can export any subsystem (including internal subsytems) and also import like that. (except its slightly broken for internal subsystems, I will fix that to) 

in the GUI, the export function (UI button/menu and HCOM sapa command exports the entire model regardless of what system is currently in active (which one you are inside in the view). However, the import function (UI button/menu) or HCOM repa commands will try to load into the currently active system. This will of-course fail, as you can only export the full model, unless you have manually hacked the exported xml file, or are "luck" that all of the components names match anyway.

So how should this work? I propose (but want your input)

- UI import/export button and menu actions should import/export parameters for the entire model.
- sapa and repa commands should also do this by default, but there should be an option to export/import to a particular system either specified by a name argument, or a flag '-this' or '-self' or -'current' if you want the system that you are currently inside (including sub-sytems)
- There could also be added right-click context menu alternatives for subsystems, to import/export parameters for that particular system. (A graphical alternative to the extended sapa, repa commands)

**Comment by robbr48** [comment]
I support the suggestion. It is good that the default behavior is easy to understand, and that more advanced features are hidden. I propose that the flag should be `-currentSystem` to make it clear, perhaps with `-c` as an abbreviation.

**Comment by IngoSt** [comment]
@peterNordin 
I support the suggestions. Would be great. By the way, is it possible to add there a option (e.g. -component compoentname) to save/load the parameterset of One (or several) components only? E.g. in the AeroAircraft6DOFSS component are >80 parameters, there would it be nice if the user could save there different parameter setups to model different aircraft types "A320", "Concorde", F16, etc...
