### ISSUE TITLE
"while - repeat" command missing in HCOM documentation

### ISSUE THREAD

**Issue by mrejster** [Hopsan/hopsan#1902]
while (i<5)
   * some code *
   i=i+1
repeat

constructions are possible in HCOM files.
This functionality is not described in the documentation.

**Comment by peterNordin** [comment]
@robbr48 Do you have the users guide for the old hopsan classic version? I remember it covered HCOM quite thoroughly, maybe we can get some ideas from there on how to update the current documentation. Otherwise I guess we should just write down all things that can be done right now
