### ISSUE TITLE
Add component directly on work pane should be double-click

### ISSUE THREAD

**Issue by larsviktorlarsson** [Hopsan/hopsan#1908]
**Is your improvement request related to a problem? Please describe.**
*I always get frustrated when I am dragging components around and accidentally click on the work pane, because a text box appears in which I can search and add a component.*

**Describe the solution you'd like**
*The search box should appear on double-click instead of single-click.*

**Comment by robbr48** [comment]
I agree. Single-click is less tiring for your index finger, but also causes more frustration. I made the single-click implementation to get some user feedback, and most people seem to prefer double-click.
