### ISSUE TITLE
Non-double system parameters are not pasted when copying components between models

### ISSUE THREAD

**Issue by robbr48** [Hopsan/hopsan#1927]
**Describe the bug**
When copying components using system parameters, the system parameters shall also be copied and pasted in case they don't already exist in the model. This currently only works for parameters of type `double`.

**To Reproduce**
1. Add a C-type piston component
1. Define a boolean system parameter
2. Map the `use_sl` constant to the system parameter
3. Copy the piston
4. Paste the piston into a new model
5. The system parameter will not be added

**Expected behavior**
The boolean system parameter should be added in the new model.

**Additional information**
The reason seems to be that NumHop is used to evaluate the parameter, and it relies on `evaluateDoubleParameter`to check if the parameter exist in the system.

**Comment by peterNordin** [comment]
Closed by #1948
