### ISSUE TITLE
broken dependency for hopsan_2.14.0.20200501.1239_eoan_amd64.deb

### ISSUE THREAD

**Issue by matthiasliermann** [Hopsan/hopsan#1941]
**Describe the bug**
Dependency issue with hopsan_2.14.0.20200501.1239_eoan_amd64.deb. Install failed.

**To Reproduce**
install hopsan_2.14.0.20200501.1239_eoan_amd64.deb on Ubuntu 19.10: 

```
sudo apt install ./hopsan_2.14.0.20200501.1239_eoan_amd64.deb 
[sudo] password for admin: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'hopsan' instead of './hopsan_2.14.0.20200501.1239_eoan_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 hopsan : Depends: libpythonqt-qt5-python3-3 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Expected behavior**
expect install without error

**Comment by peterNordin** [comment]
This was strange, the pythonqt packages no longer exist in the repository for eoan, but I had them inside my eoan build environment. Possibly that environment was created while eoan was still in beta, and maybe the packages were removed later. Its the only reasonable explanation.

Anyway, new eoan packages have uploaded to the 2.14.0 release, let me know if they work better.
(I could install them on my 19.10 machine)

**Comment by matthiasliermann** [comment]
Thanks for solving this so quickly!
