### ISSUE TITLE
The "toggle signal components visibility" function hides too much

### ISSUE THREAD

**Issue by larsviktorlarsson** [Hopsan/hopsan#1958]
**Is your improvement request related to a problem? Please describe.**
*It always frustrates me when I have a signal component that has animation, and when I want to hide only the signal lines (for instance when I want to show an interactive animation without a lot of signal lines), my animation component is hidden as well*

**Describe the solution you'd like**
*I would like to be able to override the "toggle signal components visibility", for instance by including an "Always show" option in the component.*

**Describe alternatives you've considered**
*An alternative component type (e.g. Animation) could be used to ensure that the component is not hidden when I choose to hide signal components*

**Comment by robbr48** [comment]
I vote for the suggested solution. A new component type would be really messy, since it must also be included in the simulation core.

I also think this is useful not only in animation mode, but also in the regular model view.

**Comment by larsviktorlarsson** [comment]
> I vote for the suggested solution. A new component type would be really messy, since it must also be included in the simulation core.
> 
> I also think this is useful not only in animation mode, but also in the regular model view.

Yes, I agree, it sounds like a too complicated approach to include it in the simulation core.
