### ISSUE TITLE
System crash when opening animation dialogue if the movable index does not start at 0

### ISSUE THREAD

**Issue by larsviktorlarsson** [Hopsan/hopsan#1966]
**Describe the bug**
*Hopsan crashes when animation dialogue is opened and the index of the movables does not start at 0*

**To Reproduce**
*If the bug can be reproduce, please give the steps taken to reproduce the behavior:*
1. Make a component which has animation features with several movables
2. Let the index of the first movable be idx="1" (movable idx="1")
3. Drag the component to a model
4. Go into animation mode
5. Double click on the movable to open the animation dialogue
6. Hopsan crashes 

**Expected behavior**
*Perhaps this should be checked as the library is loaded, and generate a warning? Alternatively, one could have an error dialogue that opens instead of crashing the gui*

**Comment by robbr48** [comment]
Confirmed. Hopsan accesses the movables by the order they are loaded from XML, which likely also causes problems if the movables are not sorted according to their indices.

I was able to fix this for the dialogs, but the animated components also uses the weird indexing. I need to think of a solution for this.

**Comment by peterNordin** [comment]
@robbr48 did you merge some partial fix for this ?

**Comment by robbr48** [comment]
No, but I can do that tomorrow I think.

**Comment by robbr48** [comment]
After looking some more into this, I don't think this is a problem anymore. The movables are updated in the order they are specified in the XML file, but it doesn't matter as long as each movable is updated with its own parameters. Also, they seem to be sorted in Z-level according to their index, so that the highest index is always on top.
