### ISSUE TITLE
Quantity, units and number format for display component

### ISSUE THREAD

**Issue by larsviktorlarsson** [Hopsan/hopsan#1968]
**Is your improvement request related to a problem? Please describe.**
*It always frustrates me when I add a display for my animation, and the number is too big, so that it is shown as 1e+4 instead of 10000. It is also frustrating that it always shows the value in SI unit and that the unit is not shown.*

**Describe the solution you'd like**
*It should be possible to select number format. It should be possible to select quantity and unit of the displayed output (the unit and the quantity should be shown as well)*

**Alternative solutions**
*It is possible to scale the signals with gains and then add units and text with text widgets, but this is unnecessarily messy*

**Comment by robbr48** [comment]
These are good suggestions. The quantity can already be set on the signal, but I guess non-SI units is also needed. Maybe it can just be an arbitrary string.

The main problem here is that the icon would need to be resized to match the length of the output string. Just scaling it would probably look ugly, unless we change the icon or uses a custom frame somehow.

**Comment by larsviktorlarsson** [comment]
As long as the quantity is selected in the component settings dialogue, perhaps the unit could be automatically added according to what the user has put in the "Unit Scaling" tab of the "Options" dialogue, similar as to when a quantity is set to a signal output and then plotted? Ideally, the user should also be able to change the unit of each individual display as well (similar as to right-clicking on the y-axis in the scope). The "Custom label" option could perhaps be used to set the label of the display (e.g "Altitude:")?

Concerning the icon scaling, one solution could be to make the background a solid color (e,g. grey) and then scale it with the string size. The background could also be skipped altogether, although I think a background should be preferred. If a custom frame is possible, that should be preferred, but perhaps this is too complicated at this stage?

**Comment by robbr48** [comment]
A custom frame would require a GUI hack, since scaling an SVG icon with a frame only horizontally would make the frame thicker on the sides than on top and bottom.

No background at all would be the easiest solution. It could also be possible to select background (and text) color as parameters, since animation mode supports changing colors of movables.

**Comment by robbr48** [comment]
@larsviktorlarsson I started working on this, but it turns out that having non-SI units is not trivial at all. All variables in Hopsan always use SI units, and non-SI units are only used for pre-processing (parameter values) and post-processing (e.g. plotting). Information on available units and quantities are not available for a component during simulation.

Is it sufficient to manually provide this information to the display component using a string and a double parameter for unit name and unit scaling?

**Comment by larsviktorlarsson** [comment]
I guess it is possible, but perhaps it will introduce an unnecessary source of error?  If so it should be clearly stated so that the user understands that it is only an animation feature (which should be clear anyways since the display is an animation component).

Otherwise, would it be possible to use the "conditional constant" parameter type? Then the user could simply choose a desired unit from a dropdown menu, and the component has its own "database" of unit scalings. Maybe combined with some sort of "Custom" option? The risk is then that the quantity and unit do not match, but this is then the users problem..

**Comment by robbr48** [comment]
Well it would be possible, but the component would need to have its own database with quantities and units. It is not possible for components to access the database in Hopsan, and even if it were, it could differ between Hopsan versions. Also users can create their own custom units. This would cause compatibility issues. I will go for the parameter solution for now and we can think more of this later.

**Comment by larsviktorlarsson** [comment]
Ok, yes that sounds like the best compromise!

**Comment by larsviktorlarsson** [comment]
@robbr48 
Suggestion: The "Description label" text string should be shown above the digits, to make it easier to place the component (the digit moves away if the label is too  long)

Also, there should be a space between the digit and the unit.

E.g: 
Altitude:
124.5 m
