### ISSUE TITLE
Cannot make large parentheses  .md file equation

### ISSUE THREAD

**Issue by larsviktorlarsson** [Hopsan/hopsan#1972]
**Describe the bug**
*If the commands \left( and \right) are used within an equation in the .md file, the shown parentheses are still normal size.*

**To Reproduce**
*If the bug can be reproduce, please give the steps taken to reproduce the behavior:*
1. Make a component with a .md file
2. Add equation to the .md file: 
3. Open description in Hopsan
4. The equation is shown with small parantheses

**Expected behavior**
*Parentheses should be larger and encapsulate both denominator and numerator of the fraction.*

**Screenshots, Model or Data files**
*If applicable, add screenshots, models or data files, that display or cause the bug.*

![image](https://user-images.githubusercontent.com/62874593/90532394-7c3dbc80-e177-11ea-9b87-ad0076ec0eab.png)

**Comment by robbr48** [comment]
@peterNordin I assume both this and #1973 are bugs in KaTeX and not in Hopsan?
