### ISSUE TITLE
Separate repository for development libraries

### ISSUE THREAD

**Issue by larsviktorlarsson** [Hopsan/hopsan#1988]
There should be an official repository for Hopsan development libraries, that is separated from the Hopsan repo. In this repo, users can have their own public libraries with components that are still under construction. 

This way, it is possible to share libraries with others and also allow others to give feedback before trying to merge new components into Hopsan master. This repo could also contain temporary libraries used e.g. in courses and teaching.

It should be noted that this repo is for development libraries, which means that the users should be aware of this and thus cannot expect the components to work perfectly if working at all.

Please add additional requirments/desires in this issue before the repo is created.

**Comment by larsviktorlarsson** [comment]
Perhaps this repo could contain an example library, with example components, xml files, md files and proper naming of the different files?

**Comment by peterNordin** [comment]
The example library already exists in the default repo and is included in the hopsan release, so it should stay there.
Any library that should be shipped with hopsan "must" be in the main repository. Or one may use git submodules, but lets avoid that if possible.

**Comment by larsviktorlarsson** [comment]
> The example library already exists in the default repo and is included in the hopsan release, so it should stay there.
> Any library that should be shipped with hopsan "must" be in the main repository. Or one may use git submodules, but lets avoid that if possible.

Ok, but then the information in the readme maybe should include a path to the example library in hopsan?
