### ISSUE TITLE
Support HDF5 export in HopsanCLI

### ISSUE THREAD

**Issue by robbr48** [Hopsan/hopsan#1989]
**Describe the solution you'd like**
Move HDF5 export to HopsanGenerator, so that it can be called from both GUI and CLI.
- No duplicated code
- Maybe worse performance due to copying of data vectors

**Describe alternatives you've considered**
Duplicate HDF5 export code in HopsanCLI.
- Reduced maintainability due to duplicated code
- Better performance

**Additional context**
Related to #1976.

**Comment by peterNordin** [comment]
I don't think this belongs in the hopsan generator library, it should be a new library. Preferably  a static library that can be optionally linked with hopsancli / GUI depending on if hdf5 is available when building.

Then we don't have to deal with the problem of c-api and runtime loading.

So escentially CLI becomes dependent on hdf5 if it is available when building. But if not its still plain c++.

**Comment by robbr48** [comment]
The purpose of HopsanGenerator is to generate different kind of files, so in one way data export could belong there. But you are right that it would be nice to remove the C-api and use static linking. I will try this approach.
