### ISSUE TITLE
Multicore support for hopsanCLI

### ISSUE THREAD

**Issue by mrejster** [Hopsan/hopsan#1999]
**Is your improvement request related to a problem? Please describe.**
Multicore seems unsupported (or at least undocumented) for the hopsanCLI application?

**Describe the solution you'd like**
Add the option to use multicore simulation with the hopsanCLI application

**Describe alternatives you've considered**
Manually firing up multiple hopsanCLI instances, but using the complex optimization method requires each run to be finished before updating parameters. For other techniques it might be possible, if different evaluations can be run simultaneously.

**Additional context**
-

**Comment by robbr48** [comment]
It is currently hard-coded to use single-threaded simulation. It should be easy to solve with a new flag for multicore and/or number of threads.

**Comment by peterNordin** [comment]
Hmm this is embarrassing, it never occurred to me that it was not available. It does run with multiple cores when doing validation tests of models. But the main simulation call does not.

**Comment by robbr48** [comment]
I believe this is an artifact from when the TBB dependency was used, and we didn't want CLI to depend on it. Or maybe we just wrote the CLI simulation code before the multithreading code was added, and then just forgot about it...
