### ISSUE TITLE
Warning: Failed to load component of type: CppComponent

### ISSUE THREAD

**Issue by Satinelamp** [Hopsan/hopsan#2014]
*When I open Hopsan, I got warnings:*
`Warning: Failed to load component of type: CppComponent`
`Warning: Failed to load component of type: ModelicaComponent`
Here is the screenshot:
![1](https://user-images.githubusercontent.com/62006565/98978405-e38bc280-2554-11eb-89f6-f8d08c706883.png)
 
and when I open HoLC, I got another warning like the following screenshot:
![3](https://user-images.githubusercontent.com/62006565/98978423-e8e90d00-2554-11eb-9f83-c3caf5c831ea.png)

My question is: Do I install Hopsan in the wrong way?
I used the package from Github:
![Snipaste_2020-11-13_02-10-16](https://user-images.githubusercontent.com/62006565/98978751-63b22800-2555-11eb-8e69-df269cf75ec6.png)

**Comment by peterNordin** [comment]
Was it the first time you installed Hopsan, or did you have a previous version installed before ?
I think the message from HoLC is normal the first time you start, does it happen again if you start it again?

As far as I know just running the installer should be enough, but I always update my installation so I dont know if its an issue with a clean install.

**Comment by Satinelamp** [comment]
This is my first time to install Hopsan.
It happens every time I start HoLC.

**Comment by peterNordin** [comment]
Hmm, I just tried it myself (with an upgrade) and I also got those Warnings. 
I will investigate.

Also I got a red "Development version" on the splash screen, did you get that to?
I dont think its related, but the build script may have failed to regenerate the splashscreen.

**Comment by Satinelamp** [comment]
Yes, I also got a red "Development version".

**Comment by peterNordin** [comment]
I dont think you need to worry about it, it may be leftover files in the default library, that should have been removed.
But I will try to verify this.

Also most of the functionality if not all of HoLC has been moved into Hopsan(GUI).
So if you want to create your own library I recommend you use the "+Create external library" button in hopsan instead of using HoLC it is not being updated any more. We should add info about this in the HoLC splash screen.

**Comment by Satinelamp** [comment]
what about the following warnings when I started Hopsan:
`Warning: Failed to load component of type: CppComponent`
`Warning: Failed to load component of type: ModelicaComponent`

**Comment by peterNordin** [comment]
Yes those were the ones I meant. No need to worry about them. I have verified now, those components were removed from the code recently, and replaced with a new code generator. But we apparently forgot to remove the corresponding "component appearance files" and now it warns that those components are not available.

I will remove them for the next version.
Regarding the HoLC warning it can be ignored as well, I wil lsee I i can fix it anyway, to avoid needless worry from new users.

I also noticed that your news feed is not loading. Dont know what is going on there, "it works for me". It is supposed to look for a rss feed generated by/hosted on GitHub.

**Comment by Satinelamp** [comment]
Does this mean that Hopsan won’t support Modelica any more? Or we will have another method to build and load Modelica components?




发自我的iPhone


------------------ Original ------------------

**Comment by peterNordin** [comment]
Modelica is still supported. But now (since version 2.15) a new code generator is used. It generates all of the code c++ code that "wraps the modelica code". Previously we had a special component, the "ModelicaComponent", that loaded the code somehow.

I did not implement this new generator so I am not familiar with the details. Maybe @robbr48 has some information to add.

**Comment by Satinelamp** [comment]
Regarding the TLM method used in Hopsan, I googled it, it seems this is a method from electromagnetic theory, so if I plan to use it on a fluid system, is there any recommended introductory material about how to use it on other domains?

**Comment by peterNordin** [comment]
If you send me an email to jpn.peter@gmail.com I can send you a document. I am trying to figure out if I can publish it together with Hopsan (I did not write it). But I can send it to individuals asking for it.

**Comment by robbr48** [comment]
Modelica components are now created from within HopsanGUI. HoLC is deprecated and will be removed in the future. The Modelica support has been improved with more integration methods, support for conditional statements and improved numerical robustness. You create libraries and components directly from the component library widget by right-clicking on "External Libraries" and selecting "Create New Library". Then right-click on the new library and select "Add New Component".
