### ISSUE TITLE
Default Library : Q_type_Fixed_Displacement_Motor : missing parameter units

### ISSUE THREAD

**Issue by OwenDavid** [Hopsan/hopsan#2025]
If we open the properties for this object we can see that the leakage coefficient, *c_lm* has no associated units.

If we compare this to the Q type pump, we see that a leakage coefficient unit of *(m^3/s)/Pa*

Experimenting with values in this unit, such as, 10e-12, yields reasonable results in the motor.

**Describe the solution you'd like**
*Confirm the units of motor leakage coefficient*
*Add the correct units to the default library object*

**Comment by robbr48** [comment]
The suggested unit is correct. It should be the same for both components. We should update the component, and preferably also have a non-zero default value to give the user a hint of which values are reasonable to use.
