### ISSUE TITLE
Default Library : rotation of 'SUM' signal icon

### ISSUE THREAD

**Issue by OwenDavid** [Hopsan/hopsan#2026]
The summation signal icon displays a capital Sigma ( Σ )

Rotation or mirroring of this icon changes the sigma to read as either a 'W', 'M', or '3'.

The 'W' and 'M' cases are particularly clear and can lead to confusion in the signal path.

**Describe the solution you'd like**
*Modify icon to prevent rotation of graphic when rotating or mirroring ports.*

**Comment by peterNordin** [comment]
I noticed this is also a problem for some other similar components, I will look through them.
