### ISSUE TITLE
Default Library : Standardise Oil Density Default Setting

### ISSUE THREAD

**Issue by OwenDavid** [Hopsan/hopsan#2029]
Some objects in the library have an oil density input variable. However, the default value varies with different components.

For example, here we can see two hydraulic components that would likely be used in the same model.

One has an oil density of 890 and the other 860.

Should this be variable be standardised for all components in the default library?

*Suggestion for default density of 870 kg/m^3*

![image](https://user-images.githubusercontent.com/66214518/103301096-d9d4f600-4a00-11eb-9b3e-68e9c12ffb0e.png)

**Comment by robbr48** [comment]
I agree that it should be consistent. The most common density unit in the default library seems to be 890 kg/m^3, which is rather high for a hydraulic oil. I think 870 is a reasonable suggestion. 

A more elegant solution could be to automatically add a system parameter for common parameters like density. Whenever a component with a density parameter is added, the system parameter is created. When adding other components, their density parameters becomes automatically mapped to the existing system parameter. This needs some more thinking though. For now we should just update the default values to make them consistent.

**Comment by OwenDavid** [comment]
Would Bulk modulus be another good example of an environmental parameter that could be standardised automatically?

For example, we can see this parameter in the hydraulic volume and the long lines with viscoelastic walls. Both have a default of 1e+9.

**Comment by robbr48** [comment]
Sure, and probably also other common parameters like viscosity and tank pressure. But this is a future project. Right now we should just make sure that the default values are consistent.
