### ISSUE TITLE
New Component: Differential Pressure Gauge

### ISSUE THREAD

**Issue by OwenDavid** [Hopsan/hopsan#2030]
A differential pressure gauge is a useful real world tool to identify the pressure drop across a point of interest in the system.

Could we implement a new object with two pressure inputs and simple code to return the difference or perhaps abs(difference)?

This would prevent the use of several signal blocks and a scope to calculate the same.

Otherwise, would it be trivial to add this as an output variable to relevant objects in the library (restrictors, orifices, etc) so that it would feature in the plot list or would it increase the computation cost for all simulations with only a marginal return, i.e. if the output was used/plotted?

**Additional context**

**Comment by OwenDavid** [comment]
Encouraged by the addition of the mechanical rotational power sensor by another contributor I have created this new component.

Please see the attached files for my submission of a differential pressure transducer with the addition of a second input port and updated SVG file.

Perhaps someone can comment on whether the addition of an absolute differential is useful or not?

[HydraulicDifferentialPressureSensor.zip](https://github.com/Hopsan/hopsan/files/5755130/HydraulicDifferentialPressureSensor.zip)

**Comment by robbr48** [comment]
This is a good idea, I think it could be useful for many users! The code looks correct. I have only some minor comments:

1. To avoid confusion there should be only one output port. A separate abs component can be used if you need the absolute value.
2. The icon should have the same dimensions for ISO and user type. 
3. The standard symbol for differential pressure gauges appears to have two connections at the bottom, like [this](https://commons.wikimedia.org/wiki/File:Symbol_Differential_pressure_measuring_instrument.svg). I think we should conform to this. It will make it slightly harder to connect it though, so this is really a matter of taste.

Do you want to make a pull request, or do you want me to make one for you?

**Comment by OwenDavid** [comment]
Taking each point in turn,

1. Agree, has been changed to single output port
2. Ok, done
3. Agree, the connection of two lines close together looks quite ok when the lines attach to the ports from each side. However, if the icon is then moved and the lines cross, as in the highest gauge in the screenshot, then we cannot determine which port connects to which. There appears to be a position and rotation that uncrosses the lines in most cases of connecting to C/Q ports without much separation.

The updated files attached. Please go ahead with the pull request on my behalf. Thanks!

[HydraulicDifferentialPressureSensor_rev2.zip](https://github.com/Hopsan/hopsan/files/5772134/HydraulicDifferentialPressureSensor_rev2.zip)



![image](https://user-images.githubusercontent.com/66214518/103687414-84fd2680-4f90-11eb-8879-d25ef26570ba.png)

**Comment by robbr48** [comment]
Looks good! The problem with overlapping lines can be avoided at least partly by rotating the ports P1 and P2 90 degrees. In this way the two lines on the icon can also be removed, so that the ports attach directly on the circle. I made some changes myself, what do you think?

[HydraulicDifferentialPressureSensor.zip](https://github.com/Hopsan/hopsan/files/5786684/HydraulicDifferentialPressureSensor.zip)

**Comment by OwenDavid** [comment]
The changes break the ISO symbol layout. See screenshot.

As you proposed my rev2 matched the ISO and Hopsan symbols, i.e. same pixel size and two lines. To my eye this seems to be the clearer symbol except in cases of overlapping lines. I expect the user will seek to resolve this by rotation and optimum placement of the sensor. rev2 is the way to go in my opinion.

![image](https://user-images.githubusercontent.com/66214518/104010496-de41a180-51ac-11eb-90fc-434e158e7ed9.png)

**Comment by OwenDavid** [comment]
Regarding overlapping lines - it seems there is always a sensor position/rotation that can resolve this. So it is simply a case of tria/error for the user.

Given the significant incidence of overlapping lines where the sensor joins the port, i.e. it is difficult to see what is connected to what, I don't think the overlapping lines in the sensor icon are a deal breaker.

Pleased to have contributed this and thanks for the assistance with development. I'm using it in several models already!

**Comment by robbr48** [comment]
Ops, I forgot to save the ISO icon before creating the zip package :)

If I understand you correctly, you want to keep the two lines for both iso and user icon? It is really a matter of taste. Removing them makes the icon more consistent with existing sensors. Also, connectors to sensors are dashed by default while the lines are not. On the other hand, the lines makes it easier to distinguish from non-differential sensors.

Do you want me to create a pull request, or do you want to do it yourself?

**Comment by OwenDavid** [comment]
Yes, preference to keep two lines for both symbols. 

Can you please create pull request - I am quite new to contributing to open source projects and to github so am taking it one step at a time!
