### ISSUE TITLE
GUI: Improving Mouse Over Feedback from sensors and ports

### ISSUE THREAD

**Issue by OwenDavid** [Hopsan/hopsan#2039]
If we move the mouse pointer over any component in the GUI then some information is revealed. Move the mouse away and it disappears.

Typically, this is the name, bounding box, port locations, and colours.

Is it possible to add more information to be revealed during a mouse over event?

For example, when connecting sensors and gauges, could the C/Q ports it is connected to also be highlighted? By definition, a sensor is only relevant by virtue of the fact it is connected to something. However, we cannot easily reveal this information in the GUI. This is especially true if the dashed sensor lines lie on top of a fluid line.

In the first screenshot, we see the typical mouse-over behaviour of a sensor.

![image](https://user-images.githubusercontent.com/66214518/103689961-4cf7e280-4f94-11eb-9588-d945400e78f9.png)

If we could highlight the dashed connection line and the connected port as shown below then the sensor is fully described. 

It would be useful to not only highlight the two ports with matching colors, blue in this case, but color the dashed connecting line in the port color to really emphasise the connection.

The proposed is shown in the second screenshots of a mechanical and hydraulic sensor.

![image](https://user-images.githubusercontent.com/66214518/103690537-32723900-4f95-11eb-841c-cb9761ba714f.png)
![image](https://user-images.githubusercontent.com/66214518/103691081-e5db2d80-4f95-11eb-8bf6-c27583ccf2d3.png)

*Would this be a trivial change? Do the sensor objects contain information as to what their ports are connected too? Or is this information, i.e. what connects to what, stored elsewhere and easily accessible to the GUI?*

**Comment by robbr48** [comment]
This should be possible. Each component has a list with pointers to its connectors. But maybe this should apply to all connectors and all components? So that all connectors that are connected to a component are always highlighted when the component is hovered? That would actually be easier to implement, since we wouldn't need to distinguish between different types of connectors and components. I think I need to make an actual implementation to see how useful it is.

**Comment by peterNordin** [comment]
Yes good idea, especially useful for complex messy models.
A first step would be to only highlight the connectors without the same color as the ports, then we can add that later if its not to complicated. Maybe even have a toggle button for this feature if someone does not like it.
