### ISSUE TITLE
Standard Library Components: Leakage Coefficient Unit Conversion

### ISSUE THREAD

**Issue by OwenDavid** [Hopsan/hopsan#2040]
In the GUI some component parameter windows can access a unit converter. For example, for we can set a flow rate in l/min or m^3/s.

Could a new converter be added for leakage coefficients?

**Proposed Leakage Units**
*Default - m^3/s/pa (matching existing components)*
*Alternative - m^5/Ns*
*Realworld/datasheets - l/min/bar*

If I am right in thinking that the default and alternative are equivalent then the conversion factor would be 1. The change of name would accommodate the user familiar with these units.

The conversion factor for l/min/bar:

1 l/min =1.66667e-5 m^3/s
1 bar = 1e5 Pa

1 m^3/s/Pa = 1.66667e-5 / (1/1e5)

1 / 1.66667e-10 l/min/bar = 5999,988e6 l/min/bar

*finally, 1 m^3/s/Pa = 5999,988e6 l/min/bar*

As a test, a typical motor leakage coefficient of 1.067e-12 m^3/s/Pa = 0.0064 l/min/bar, so at 100 bar, this gives 0.64 l/min.

This would be relevant to many of the hydraulic components, i.e. pumps, motors, linear actuators, and hydraulic machines and assist users with industrial backgrounds or those referring to datasheets.

**Comment by OwenDavid** [comment]
*I was able to achieve the proposed by modifying the file, hopsan-default-configuration.xml and adding the following at the very end. This should enable all the components with defined leakage coefficients to utilise the unitconverter.*

Can someone please review and add this to the next release?



       <quantity>
          <quantity name="Leakage Coefficient" baseunit="(m^3/s)/Pa">
          <unit name="m^5/N" scale="1.0"/>
          <unit name="(l/min)/bar" tobaseexpr="0.001*(x)/60e5" frombaseexpr="60e5/0.001*(x)"/>
        </quantity>
    </unitsettings>
</hopsandefaults>

**Comment by peterNordin** [comment]
Yes this seems like a good idea.
@OwenDavid is a `s` missing from `<unit name="m^5/N" scale="1.0"/>` ?
@robbr48 can you verify the numbers, I did them in my head and they seem correct.

We should also add `Leakage Coefficient` to quantities in HopsanCore, and maybe even replace the recently fixed component units with the quantity names.

**Comment by OwenDavid** [comment]
Yes, agree, the unit name has a typo.

Should it not be `m^5/Ns` ?

**Comment by robbr48** [comment]
The numbers seem correct.

I think we should use parentheses when there are multiple variables in the denominator. This is however inconsistent in Hopsan already. Acceleration has the unit "m/(s^2)" (with parentheses) while density has the unit "kg/m^3" (without parentheses). We also sometimes use spaces when two units are multiplied (e.g. "kg m/s" and sometimes not ("Nm"). We should try to follow some standard for unit notation.

In this case I think it should be "m^5/(Ns)".
