### ISSUE TITLE
Invert curve in Plotwindows

### ISSUE THREAD

**Issue by bjoer37** [Hopsan/hopsan#2057]
When inverting a variable in a plotwindow it does become un-inverted when a simulation is performed. Then one need to invert it again. It is likely that the user wants to keep it inverted i.e. the same visual benefit with inverting the variable is likely still there after another simulation. 

**To Reproduce**
1. Simulate a system
2. Plot a varilble or more
3. Invert at leat one of the plotted curves
4. Simulate the model again
5. The invert will be un-ticked and the variable is thereby also un-inverted

**Expected behavior**
The invert setting in plotwindows should be preserved when simulations are ran. 

- OS: Windows 10 ver 1809 OS Build 17763.973
- Version: Info: HopsanCore 64-bit, Version: 2.16.0.20201108.1336 (Compiled in debug mode)
- Build: compile it myrself

**Comment by peterNordin** [comment]
Hmm I just realized that this functionality already exists, sort of. In the propertis dialog for a component you can check an anonymous box far to the right in the PlottSettings column. Then it will tag the data that it should be inverted (in the plot) data is still not inverted. Then any new generation will get inverted.

The control for inverting curve in the plot window, only inverts the current particular curve. If you open another plot with the same data, it will not be inverted.

So essentially, any changes that you want to affect all instances of the data, i.e. all curves, should be med in the model. In this case in the PlottSettings in the properties window. 

Any changes that should only affect a particular curve in a particular plot, should be made in the plot window. Such changes should not affect other instances of the data. (One exception is the generation timescale function).

Maybe I should make it more clear in the properties dialog what the checkbox does.

**Comment by bjoer37** [comment]
Sort of. But, my opinion is that all you say make sense except if a curve is inverted in a plot window it shall be inverted in all following simulations, in that plot window, until the invert option is unticked. I have no problem with different invert status between generations.

**Comment by peterNordin** [comment]
Correction to what I previously said, if you click the invert button in the plotwindow, it will actually invert all instances of that curve at that particular generation in all plotwindows. But this is the intended behavior.

I am clarifying the UI elements and tooltip for the controls. But I am not sure if I want to allow making changes to the model from the plot window. Possibly the individual plot window could remember if you have invert settings that  differs from the model, and then remember it until the windows is closed, but this adds complication.

If you know that you want to invert the curve, then set it in the model /then it will also be saved)
But lets see what Robert thinks. Maybe it could be useful to remember locally in a plot window (plot tab actually)

**Comment by peterNordin** [comment]
This turned out to be more complicated then I thought, please have a look at the linked pull request description.
