### ISSUE TITLE
Optimization fails to start on Windows

### ISSUE THREAD

**Issue by robbr48** [Hopsan/hopsan#2064]
**Describe the bug**
When clicking start optimization, nothing happens and the program freezes.

**Hopsan version**
It happens on Windows with 2.17.0, but seems to work fine on Linux. When I downgrade to 2.16 it works again on Windows.

I will do some more testing. Unfortunately my debugger does not work on Windows at the moment, so it is difficult to trace the error. It could be related to changes to the progress bar. I tried with progress bar both enabled and disabled though, and there were no difference. I also tried both multithreaded and singlethreaded simulation with no effect.

**Comment by peterNordin** [comment]
My debugger is working and I found where the problem lies,
Its not the progress bar, its in OpsWorker.cpp line 147, the for loop get stuck looping for ever, due to the counter i getting decremented on line 174. At least in my test case.

**Comment by peterNordin** [comment]
why it works on Linux I do not know, code should not depend on platform. unless we trigger undefined behavior somehow.

**Comment by peterNordin** [comment]
well, the code depends on opsRand() so random functionality my differ

**Comment by peterNordin** [comment]
Actually line 165: ```x = min + opsRand()*(max-min)``` with `min=0, max=1` always return the same value. So the random function does not seem to be producing random values. Either the new random code is wrong, or not initialized properly, or there is a bug in the MinGW64 version that we are using.

**Comment by peterNordin** [comment]
Aha, found the problem, the random_device, default_random_engine and maybe distribution need to be static, otherwise the are recreated on every call and will give the same value since it returns the first random value in some sequence of random values. Not sure how it works exactly, working on PR

**Comment by peterNordin** [comment]
Even though I have fixed the problem (I hope), the program seems to generate the same sequence of random numbers every time it runs.
Not sure I like that. The old code seem to seed based on the current time, I do not know how the new c++11 code seeds.
