### ISSUE TITLE
Loss calculation shows wrong value for domain-specific losses

### ISSUE THREAD

**Issue by robbr48** [Hopsan/hopsan#2098]
**Describe the bug**
When a component for example only has mechanical ports, the "mechanical losses" should be the same as "total losses". It is however much smaller. It seems like only the last log interval is considered for domain specific losses.

**To Reproduce**
1. Simulate a model
2. Click on "Calculate Losses"
3. All domain-specific losses will be wrong

**Expected behavior**
The domain-specific losses should sum up to the total losses in each component.

**Additional information**
Related to #540.

**Comment by peterNordin** [comment]
I was able to fix domain specific losses being wring for non-multiport components, not sure if multiport ones are still broken.
However the added energy output confuses me, it prints the number twice
`Added " + QString::number(it.value()/div) + " "+it.key()+" "+energyOrPower+": <b>" + QString::number(it.value()) + unit+"`
(I added the it.key() part) 
Why is the value included twice, once with /div and once with only the value expressed in "unit"
