### ISSUE TITLE
Model changes behaviour after disconnecting and reconnecting

### ISSUE THREAD

**Issue by robbr48** [Hopsan/hopsan#2122]
**Describe the bug**
A SignalSum is connected to two AngleTransducers. It gives the wrong output in one model, but correct in an identical reference model. Removing and re-connecting one of the connections makes the output correct again.

**To Reproduce**
Not reproducable. Seems to be different behaviours on different computers.

**Hopsan version (please complete the following information):**
 - OS: Windos 10
 - Version: 2.19.1
 - Build: Confirmed both on official build and development build

**Comment by robbr48** [comment]
I found the error in the sort order of signal components. It seems like ReadMultiPorts are not sorted properly. It only uses the first connected port, and ignores the rest.

**Comment by peterNordin** [comment]
I was looking at the code and trying to understand what happened, did it completely ignore one of the components or did it just sort it wrongly randomly ?

**Comment by robbr48** [comment]
It only considered the first connection to the multi port. The rest of the connections were ignored. If you were lucky those component were sorted b efore the multiport component, but it depends on the order the components and/or the connections are added to the model.

**Comment by peterNordin** [comment]
Closing manually, ("Resolvs" was misspelled)
