### ISSUE TITLE
Spectrum/FFT dialog Crashes GUI if simulation was stopped by stop component

### ISSUE THREAD

**Issue by Tirpitz93** [Hopsan/hopsan#2132]
**Describe the bug**
FFT/Spectrum dialog causes program to crash if simulation run was stopped by component.

**To Reproduce**

1. Add component and connect as per screenshot:
![image](https://user-images.githubusercontent.com/6187560/168992870-e2d1ca75-87d8-4aa4-b5ee-58edc39efb66.png)
4. Simulate the model
5. View the scope graph, use the FFT button to view spectrum.
7. The program will crash

**Expected behavior**
I would expect a spectrum of the signal up to the point the simulation was stopped to be displayed, as with the signal graph

1. Add component and connect as per screenshot:
![image](https://user-images.githubusercontent.com/6187560/168992672-b28ba456-176c-4624-a1bf-e86c42ce337b.png)
4. Simulate the model
5. View the scope graph, use the FFT button to view spectrum.
**Screenshots, Model or Data files**
*If applicable, add screenshots, models or data files, that display or cause the bug.*

**Hopsan version (please complete the following information):**
*Version information is shown in the message widget when HopsanGUI is started*
 - OS: Windows 10
 - Version: HopsanCore: 2.19.1.20211105.2150
                HopsanGUI : 2.19.1.20211105.2150
 - Build: Official build

**Additional information**
*Add any other context/information about the problem here.*
[min_crash_stopped_sim.zip](https://github.com/Hopsan/hopsan/files/8714505/min_crash_stopped_sim.zip)

**Comment by robbr48** [comment]
This seem to happen because simulation time is always logged using specified number of log samples, while the data variables are only logging the part that is actually simulated. If simulation is not stopped, time and data vectors will have the same size. The FFT code expects equal size and will crash otherwise. A simple fix should be to limit the size of the time vector as well.
