### ISSUE TITLE
HopsanGUI crashes when attempting to view the source of a missing block

### ISSUE THREAD

**Issue by Tirpitz93** [Hopsan/hopsan#2144]
**Describe the bug**
This may seem silly but there should probably a guard against this.
When using context menu to examine the source code for an unavailable block the gui crashes. 

**To Reproduce**
*If the bug can be reproduce, please give the steps taken to reproduce the behavior:*
1. Add component from library.
2. Save model
3. Close model
4. Unload library
5. re-open model
6. right click/context menu on missing block -> view source
7.  Tada: `hopsangui.exe has stopped working`
![image](https://user-images.githubusercontent.com/6187560/196122226-9855de53-249d-49d9-a1ba-3e0642534344.png)

**Expected behavior**
* A useful error message when attempting to access unavailable resources.
**Screenshots, Model or Data files**
None

**Hopsan version (please complete the following information):**
*Version information is shown in the message widget when HopsanGUI is started*
 - OS: Windows 10
 - Version: 2.19.1
 - Build: **Official** 
![image](https://user-images.githubusercontent.com/6187560/196121749-c536827f-0465-4075-9101-55894a2f499a.png)

**Additional information**

**Comment by robbr48** [comment]
Confirmed. The problem is that missing components has a type name, but no appearance data. The code here assumes that there is appearance data available for every type name. A simple error check will resolve this.
