### ISSUE TITLE
FMU Export Fails on Linux

### ISSUE THREAD

**Issue by MarkusBagge** [Hopsan/hopsan#2148]
**Describe the bug**
Exporting to FMU1 or FMU2 fails on Linux.

**To Reproduce**
Hopsan generator log last lines are;

> ...
> All required files found.
> Compressing files
> File '../Restrictor.fmu' not found in directory '/home/markus/Dokument/tmp/FMU2/fmu-stage'
> 

Then Hopsan GUI shows message

> [21:40:45] Error: Failed to export FMU 

**Screenshots, Model or Data files**
[Restrictor.zip](https://github.com/Hopsan/hopsan/files/9896789/Restrictor.zip)

**Hopsan version (please complete the following information):**
*Version information is shown in the message widget when HopsanGUI is started*
 - OS: Debian Linux
 - Version: 64bit,  2.20.0.20220711.1354
 - Build: Official

**Comment by MarkusBagge** [comment]
There is a 'modelDescription.xml' in the fmu-stage folder.
And there is a 'Restrictor.so' in the 'fmu-stage/binaries/linux64' folder.
Just a thought: Can it be that compression has some package dependency which is missing?

**Comment by peterNordin** [comment]
Did you download the deb from the github releases page or install it via "snap" (I think snap is available in Debian).
On Linux the "zip" package is required, so check if that is installed

**Comment by peterNordin** [comment]
It seems that the deb package does not directly depend on zip, so if you can solve the problem by installing it, I will add it as a dependency.

**Comment by MarkusBagge** [comment]
I added the "zip" package and can confirm this solved the problem. Thanks!
