### ISSUE TITLE
Ground electrical component connector bug

### ISSUE THREAD

**Issue by JorgeLL1729** [Hopsan/hopsan#2165]
**Describe the bug**
The component Q-type ground in the Electric->Sources is actually a C-type ground.

**To Reproduce**

1. Create a circuit
2. Try to close it using a Q-type ground

**Expected behavior**
Q-type connection insted of a C-type.

**Screenshots, Model or Data files**
*If applicable, add screenshots, models or data files, that display or cause the bug.*

**Hopsan version (please complete the following information):**
 - OS: Windows 10
 - Version: [e.g. HopsanCore 64-bit, Version: 2.20.0.20220711.1354
                       HopsanGUI 64-bit, Version: 2.20.0.20220711.1354]
 - Build: Official

**Comment by Tirpitz93** [comment]
Just encountered the same issue.


Build info 2.20.0.20220711.1354

**Comment by Tirpitz93** [comment]
Is the fix as simple as changing  `ComponentC` to `ComponentQ`?

```
...
class ElectricGround : public ComponentC
{

private:
     Port *mpPel1;
     int mNstep;
     //Port Pel1 variable
     double uel1;
     double iel1;
     double cel1;
...
```

**Comment by peterNordin** [comment]
I dont think that just changing the Class type will be enough. Q and C components work differently.
I will forward this issue to the person who wrote the code (its generated from mathematica) but for such a simple component maybe we can rewrite it manually. But it was to long ago for me, so I cant do it easily right now.

Can you try using a Q-type voltage source instead ?
I think it will behave as a ground if you set the voltage to 0, (but I am not entirely sure).
