### ISSUE TITLE
Failed to load .dll of generated FMU

### ISSUE THREAD

**Issue by till12mann** [Hopsan/hopsan#2187]
I created an FMU using pythonfmu, but when I try to import it into Hopsan it says :

![image](https://github.com/Hopsan/hopsan/assets/151921198/254d36e8-7c58-4390-9c43-7e484d700b8c)
 
Any Ideas how I can fix that ?

**Comment by robbr48** [comment]
I have never worked with pythonfmu, have you tried to validate the FMU using one of the tools listed here?

[https://fmi-standard.org/validation/](https://fmi-standard.org/validation/)

If validation passes, can you attach the FMU so we can have a look at it? (or send it privately if it is confidential)

**Comment by till12mann** [comment]
@robbr48 I created a very simple one. Just two inputs and one output. If i check it with that tool it says :

ModelStructure/InitialUnknowns does not contain the expected set of variables. Expected {intOut} but was {}.

[fmu2.zip](https://github.com/Hopsan/hopsan/files/13474534/fmu2.zip)

**Comment by robbr48** [comment]
I tried to check the FMU using FMI Compliance Checker, and it says there is a dependency missing. According to dumpbin, the FMU requires python3.dll. Do you have Python 3 on system path? You could also try to manually copy python3.dll to the hopsan/bin folder.

**Comment by till12mann** [comment]
Alright, after manually copying the .dll file to the hopsan/bin folder, I can now simulate my model. 
Unfortunately, it's not doing the multiplication I intend to do. I also switched the multiplication into the do_step() but that didn't change anything. Where do I program the functionality of the FMU?
