### ISSUE TITLE
[09:55:19] Warning: I found old log data on disk and will not remove it because another instance of Hopsan is running

### ISSUE THREAD

**Issue by ishengyeh** [Hopsan/hopsan#2229]
**Describe the bug**
*A clear and concise description of what the bug is.*

**To Reproduce**
*If the bug can be reproduce, please give the steps taken to reproduce the behavior:*
1. Add component A and B
2. Connect them
3. Simulate the model
4. The program will crash

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**Screenshots, Model or Data files**
*If applicable, add screenshots, models or data files, that display or cause the bug.*

**Hopsan version (please complete the following information):**
*Version information is shown in the message widget when HopsanGUI is started*
 - OS: [e.g. Windows 10, Linux Ubuntu 18.04, MacOS Sierra]
 - Version: [e.g. HopsanCore 64-bit, Version: 2.9.0.20180912.0739
                       HopsanGUI 64-bit, Version: 2.9.0.20180912.0739]
 - Build: Is this an **official** build downloaded from the web page, or did you **compile it yourself**

**Additional information**
*Add any other context/information about the problem here.*

**Comment by ishengyeh** [comment]
Dear Hopsan developers,  Sorry for the confusion.  I used the latest 2.22.0 to open an existing hmf file.  It failed sith the error message shown below: [09:55:19] Warning: I found old log data on disk and will not remove it because another instance of Hopsan is running.  I even reboot my machine to make sure this is the only active hopsan job.  However, the issue persists.  Could you please let me know what is going on, am I missing something?  Thanks.  BTW, the last version which can open this hmf file is 2.18.  Your advice will be highly appreciated.

**Comment by robbr48** [comment]
Hi,
I don't think the warning is related to the crash. The old log data will not affect the current instance of Hopsan; removing it is only for saving disk space. I would guess there is something wrong with the hmf file. It could also be that the model actually opens correctly, but the components are not centered in the view - the workspace size was increased lately, which might have this affect on old models. Can you try to zoom out and search the entire workspace for your model (assuming of course there is a workspace)?

**Comment by ishengyeh** [comment]
Hi, thanks a lot.  You are correct, the files actually was successfully loaded.  I just have to search all over to find it.
Appreciate your help.
